// react-todolist/src/components/TodoList.js
import React from 'react';
import styled from 'styled-components';
import TodoItem from './TodoItem';
import { useTodoState } from '../TodoContext';

const TodoListBlock = styled.div`
  flex: 1;
  padding: 20px 32px;
  padding-bottom: 48px;
  overflow-y: auto;
`;

function TodoList() {
  const todos = useTodoState();

  return (
    <TodoListBlock>
      {todos.map(todo => (
        <TodoItem
          key={todo.id}
          id={todo.id}
          text={todo.text}
          done={todo.done}
        />
      ))}
    </TodoListBlock>
  );
}

export default TodoList;

// vue-my-todolist/src/components/TodoList.vue
<template>
  <div id="todolist">
    <todo-item v-for="(todo) in todos"
      v-bind:key="todo.key"
      v-bind:todo="todo"
    />
  </div>
</template>

<script>
import TodoItem from './TodoItem.vue'

export default {
  name:'TodoList',
  components: {
    TodoItem
  },
  computed: {
    todos() {
      return this.$store.state.todos;
    }
  }
}
</script>

<style lang="scss">
#todolist {
	flex: 1;
	padding: 20px 32px;
	padding-bottom: 48px;
	overflow-y: auto;
}
</style>
